## Data Preprocessing Parameters ##

preprocessing:
  drop_columns:
    - customerID

  binary_mapping:
    Yes: 1
    No: 0

  fillna_strategy: median

  one_hot_encoding:
    drop_first: true



## Model Training Parameters ##

model:
  type: RandomForestClassifier

  random_forest:
    n_estimators: 200
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    class_weight: balanced

## Train/Test Split Parameters ##

training:
  test_size: 0.2
  stratify: true